### ISSUE TITLE
Handle NAC feature enablement via OADP for tech preview and GA scenarios 

### ISSUE THREAD

**Issue by weshayutin** [migtools/oadp-non-admin#47] opened 2024-04-16 19:15 UTC

**Comment by sseago** [comment] 2024-04-16 19:24
We might want to rename the issue, but I'm unclear on the name. The issue is not the tech-preview flag -- we have that already. The issue is that the Features section of DPA is for enabling/disabling things that are tech preview, but I'm thinking we may not want to tie creating the NAC deployment to whether tech preview feature is enabled, since once this is GA, it's no longer tech preview and always enabled.

I think there are 2 different things here:
1) enable tech preview feature -- this may be tied to customer support -- i.e. they enable it because we're supporting them for this feature
2) actually turn on NAC for a given OADP instance.

One reason to separate these is once this feature is GA, it's no longer tech preview, so the Features section goes away. If we had "enable tech preview feature" (in DPA features) and "turn on NAC controller" (in regular DPA) as separate fields, then once we remove the tech-preview flag, we're done. If we don't have this, then we'll have to come up with a completely different way of turning on the NAC  controller once 1) goes away.

**Comment by shubham-pampattiwar** [comment] 2024-04-17 20:19
@sseago @weshayutin How about this:
- For OADP 1.4 when NAC is for sure a tech preview feature, the way to enable NAC depends on values of 2 spec fields:
    - `dpa.spec.features.enableNAC: true`
    - `dpa.spec.NonAdmin.enable: true` 
    - NAC feature is only enabled if both the above spec boolean are true
- For post OADP 1.4+ scenario when the NAC feature will be GA, in our Operator code we update the NAC feature enable requirement to only have `dpa.spec.NonAdmin.enable: true` flag and this will be part of the release notes where we mention about NAC GA.
Does this proposed solution sound good for our scenario ?

**Comment by kaovilai** [comment] 2024-04-17 20:22
I think `dpa.spec.NonAdmin.enable: true` is enough. tech preview features shouldn't need to be enabled in two places, but we can communicate to user in status struct that the reconciled dpa has unsupported features.

Another option is `dpa.spec.unsupportedOverrides["techpreview-ack"]: true`

**Comment by sseago** [comment] 2024-04-17 22:07
So I'm not sure it's a question of enabling in 2 places or enabling in one place and configuring in another. I think the confusion comes from the fact that we use "enable" to mean two different things. 
1) unlocking the use of a feature that's not fully-supported.
2) turning on a controller/deployment/etc. causing it to perform actions.

For example, the node agent "feature" is always enabled in the first sense, so there's no feature flag for it, but spec.nodeAgent.enable turns it on or off -- i.e. creates the DS or deletes it.

Long term, once this is GA, we do want `dpa.spec.nonAdmin` to exist with its own enable/disable (or whatever we call it) to create the deployment. We could join both 1) and 2) above in dpa.spec.feataures.enableNAC -- but if we do so, we'll need to communicate to users that once it's GA, the config moves to a completely different location, which means their old DPA will no longer create the deployment. That's one advantage of having both fields now -- post-GA, the feature flag will always be treated as true (so it can be skipped), and the regular spec field works as it does now to create or delete the deployment. Alternatively, we could just not use the feature flag and use the spec field instead. This is analogous to 1.3.0 datamover, where no feature flag was needed, even though it was tech preview only.

One way or another, if we want 1.4.0 DPAs which start the NAC controller to work unmodified in whatever OADP makes this GA, we probably want a regular spec field outside of features or unsupportedOverrides. Whether we also want a feature flag or we'd rather just skip it is a separate question.

**Comment by shubham-pampattiwar** [comment] 2024-04-18 16:01
As discussed by the OADP engineering team, for OADP 1.4 we will have the user specifiy two fields:
- `dpa.spec.NonAdmin.enable: true` implying that the user intends to use the NAC feature, we will not be using the existing DPA spec `features` field for this.
- Alongside the above mentioned spec field we will need `dpa.spec.unsupportedOverrides["techpreview-ack"]: true` from the user, this signifies that the user is aware about the NAC's  technical preview nature and are signing up for using it.

Post OADP 1.4, when the NAC feature will be GA, we will remove the need to `dpa.spec.unsupportedOverrides["techpreview-ack"]: true` and add this change as part of the release notes.

This  workflow will be an example of how that the OADP engineering team would like to follow the feature transitions (i.e. transitions from tech preview to GA graduation) for all the future features.

**Comment by shawn-hurley** [comment] 2024-04-18 18:24
What happens if we have to remove/rename the field name `NonAdmin` after we get feedback from the tech preview? Does this approach still give us room to maneuver in that situation?

**Comment by kaovilai** [comment] 2024-04-18 18:53
Yes, because it was tech preview in nature, the struct or name could change, but best case scenario, `NonAdmin` stay where they are. Users who are not using tech preview field is not affected.

**Comment by shawn-hurley** [comment] 2024-04-18 19:11
Is the field just dropped from being reconciled if it is present and not used? I think that should be the case if we don't have the preserve unknown fields annotation on the CRD, just want to ask the question :)

**Comment by kaovilai** [comment] 2024-04-18 19:16
present and not used? like they have `spec.nac` but didn't fill out `spec.nac.enable`?

**Comment by shubham-pampattiwar** [comment] 2024-05-16 15:49
yeah, my PR got merged but this issue did not get closed, I don't know why :(

**Comment by shubham-pampattiwar** [comment] 2024-05-16 15:49
Closed via https://github.com/openshift/oadp-operator/pull/1393

**Closed by shubham-pampattiwar** 2024-05-16 15:49 UTC
